name: tvbox
options:
  xcodeVersion: 14.0
  deploymentTarget:
    iOS: 15.0
  developmentLanguage: zh-Hans
  useBaseInternationalization: true
  groupSortPosition: top
  generateEmptyDirectories: true
  carthageBuildPath: Carthage
  carthageUseXCFrameworks: true

packages:
  VLCKit-SPM:
    url: https://github.com/tylerjonesio/vlckit-spm
    version: 3.6.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    version: 5.11.2
  GCDWebServer:
    url: https://github.com/yene/GCDWebServer
    version: 3.5.7
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation
    version: 0.9.16
targets:
  tvbox:
    type: application
    platform: iOS
    sources:
      - tvbox
    resources:
      - tvbox/Resources
      - tvbox/Resources/nodejs-project
    dependencies:
      - package: VLCKit-SPM
      - package: Alamofire
      - package: GCDWebServer
      - package: ZIPFoundation
    settings:
      base:
        SWIFT_VERSION: 5.0
        SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
        SWIFT_OBJC_BRIDGING_HEADER: tvbox/tvbox-Bridging-Header.h
        OTHER_LDFLAGS: -ObjC
        FRAMEWORK_SEARCH_PATHS: $(SRCROOT)/Libraries/nodejs-mobile
        HEADER_SEARCH_PATHS: $(SRCROOT)/Libraries/nodejs-mobile/include
        INFOPLIST_FILE: tvbox/Info.plist
